### ISSUE TITLE
What about Prettier?

### ISSUE THREAD

**Issue by greglobinski** [warsawjs/topics-manager#14]
@kgajowy 
You mentioned Prettier in  https://github.com/warsawjs/topics-manager/issues/6 and self-assigned it, now the issue is closed but Prettier is not set. Do you plan to set it up?

**Comment by kgajowy** [comment]
Hi @greglobinski . In the end, I haven't submitted the PR with prettier. Would you mind submitting one? I am not sure how to keep it consistent with `.editorconfig` (it would be nice to keep it so that github could still use formatting we have in the project)

**Comment by greglobinski** [comment]
@kgajowy 
OK, I'll try
